export const credentials = {
  name: 'Edgar Hovhannisyan',
  position: 'Full stack developer',
  location: 'Russia / Moscow',
  home: 'Armenia / Vanadzor',
  phone: '+79991990895',
  email: 'ed.hovhannis1992@gmail.com',
  message: '@edocra',
  skills: [
    'HTML',
    'CSS3',
    'JavaScript',
    'React',
    'Redux',
    'TypeScript',
    'GraphQL',
    'Webpack',
    'socket.io',
    'Node.js',
    'Nest.js',
    'Next.js',
    'SCSS',
    'git',
    'RTK query',
    'Jira',
  ],
};
